In [21]:
import json
import pandas as pd

In [15]:
YEAR = 2020
files = ['cleansheet',  'cross', 'draw', 'foul', 'goal', 'loss', 'pass', 'redcard', 'save', 'shot', 'tackle', 'touch', 'win', 'yellowcard']
data_dict = {}

for file in files:
    with open('./data/{}/team/{}.json'.format(YEAR, file), 'r') as f:
        data_dict[file] = json.load(f)['data']

In [16]:
for team in data_dict['goal']:
    print(team['team_name'], team['match_played'], team['value'], team['value']/team['match_played'])

Mumbai City FC 23 39 1.6956521739130435
FC Goa 22 33 1.5
NorthEast United FC 22 33 1.5
ATK Mohun Bagan 23 32 1.391304347826087
Hyderabad FC 20 27 1.35
Bengaluru FC 20 26 1.3
Odisha FC 20 25 1.25
Kerala Blasters FC 20 23 1.15
SC East Bengal 20 22 1.1
Jamshedpur FC 20 21 1.05
Chennaiyin FC 20 17 0.85

In [19]:
clean_data_dict = {}

for file in files:
    data = data_dict[file]
    
    for team_data in data:
        team_short_name = team_data['team_short_name']
        
        if team_short_name not in clean_data_dict:
            clean_data_dict[team_short_name] = {
                'team_name': team_data['team_name'],
                'team_short_name': team_short_name,
                'match_played': team_data['match_played']
            }
            
        clean_data_dict[team_short_name][file] = team_data['value']

In [20]:
clean_data_dict

{'MCFC': {'team_name': 'Mumbai City FC',
  'team_short_name': 'MCFC',
  'match_played': 23,
  'cleansheet': 10,
  'cross': 322,
  'draw': 6,
  'foul': 344,
  'goal': 39,
  'loss': 4,
  'pass': 11050,
  'redcard': 3,
  'save': 61,
  'shot': 279,
  'tackle': 821,
  'touch': 14121,
  'win': 13,
  'yellowcard': 61},
 'ATKMB': {'team_name': 'ATK Mohun Bagan',
  'team_short_name': 'ATKMB',
  'match_played': 23,
  'cleansheet': 10,
  'cross': 250,
  'draw': 5,
  'foul': 343,
  'goal': 32,
  'loss': 5,
  'pass': 7605,
  'save': 59,
  'shot': 296,
  'tackle': 789,
  'touch': 11136,
  'win': 13,
  'yellowcard': 46},
 'JFC': {'team_name': 'Jamshedpur FC',
  'team_short_name': 'JFC',
  'match_played': 20,
  'cleansheet': 8,
  'cross': 305,
  'draw': 6,
  'foul': 310,
  'goal': 21,
  'loss': 7,
  'pass': 6564,
  'redcard': 4,
  'save': 59,
  'shot': 214,
  'tackle': 672,
  'touch': 9467,
  'win': 7,
  'yellowcard': 31},
 'HFC': {'team_name': 'Hyderabad FC',
  'team_short_name': 'HFC',
  'match_played': 20,
  'cleansheet': 8,
  'cross': 283,
  'draw': 11,
  'foul': 277,
  'goal': 27,
  'loss': 3,
  'pass': 8121,
  'redcard': 3,
  'save': 39,
  'shot': 237,
  'tackle': 595,
  'touch': 10873,
  'win': 6,
  'yellowcard': 26},
 'CFC': {'team_name': 'Chennaiyin FC',
  'team_short_name': 'CFC',
  'match_played': 20,
  'cleansheet': 6,
  'cross': 263,
  'draw': 11,
  'foul': 311,
  'goal': 17,
  'loss': 6,
  'pass': 7448,
  'redcard': 1,
  'save': 51,
  'shot': 255,
  'tackle': 663,
  'touch': 10271,
  'win': 3,
  'yellowcard': 46},
 'NEUFC': {'team_name': 'NorthEast United FC',
  'team_short_name': 'NEUFC',
  'match_played': 22,
  'cleansheet': 5,
  'cross': 235,
  'draw': 10,
  'foul': 339,
  'goal': 33,
  'loss': 4,
  'pass': 7309,
  'redcard': 1,
  'save': 42,
  'shot': 273,
  'tackle': 695,
  'touch': 10377,
  'win': 8,
  'yellowcard': 36},
 'BFC': {'team_name': 'Bengaluru FC',
  'team_short_name': 'BFC',
  'match_played': 20,
  'cleansheet': 4,
  'cross': 220,
  'draw': 7,
  'foul': 280,
  'goal': 26,
  'loss': 8,
  'pass': 7547,
  'save': 61,
  'shot': 237,
  'tackle': 547,
  'touch': 10155,
  'win': 5,
  'yellowcard': 51},
 'FCG': {'team_name': 'FC Goa',
  'team_short_name': 'FCG',
  'match_played': 22,
  'cleansheet': 4,
  'cross': 275,
  'draw': 12,
  'foul': 327,
  'goal': 33,
  'loss': 3,
  'pass': 10597,
  'redcard': 4,
  'save': 41,
  'shot': 300,
  'tackle': 754,
  'touch': 13550,
  'win': 7,
  'yellowcard': 35},
 'KBFC': {'team_name': 'Kerala Blasters FC',
  'team_short_name': 'KBFC',
  'match_played': 20,
  'cleansheet': 3,
  'cross': 289,
  'draw': 8,
  'foul': 281,
  'goal': 23,
  'loss': 9,
  'pass': 7460,
  'redcard': 2,
  'save': 58,
  'shot': 268,
  'tackle': 651,
  'touch': 10212,
  'win': 3,
  'yellowcard': 37},
 'SCEB': {'team_name': 'SC East Bengal',
  'team_short_name': 'SCEB',
  'match_played': 20,
  'cleansheet': 3,
  'cross': 221,
  'draw': 8,
  'foul': 267,
  'goal': 22,
  'loss': 9,
  'pass': 8193,
  'redcard': 4,
  'save': 64,
  'shot': 190,
  'tackle': 588,
  'touch': 10773,
  'win': 3,
  'yellowcard': 44},
 'OFC': {'team_name': 'Odisha FC',
  'team_short_name': 'OFC',
  'match_played': 20,
  'cleansheet': 1,
  'cross': 205,
  'draw': 6,
  'foul': 260,
  'goal': 25,
  'loss': 12,
  'pass': 6690,
  'save': 70,
  'shot': 213,
  'tackle': 600,
  'touch': 9386,
  'win': 2,
  'yellowcard': 50}}

In [23]:
clean_data = []
for value in clean_data_dict.values():
    clean_data.append(value)

In [26]:
clean_df = pd.DataFrame(clean_data)

In [27]:
clean_df

,team_name,team_short_name,match_played,cleansheet,cross,draw,foul,goal,loss,pass,redcard,save,shot,tackle,touch,win,yellowcard
0,Mumbai City FC,MCFC,23,10,322,6,344,39,4,11050,3.0,61,279,821,14121,13,61
1,ATK Mohun Bagan,ATKMB,23,10,250,5,343,32,5,7605,NaN,59,296,789,11136,13,46
2,Jamshedpur FC,JFC,20,8,305,6,310,21,7,6564,4.0,59,214,672,9467,7,31
3,Hyderabad FC,HFC,20,8,283,11,277,27,3,8121,3.0,39,237,595,10873,6,26
4,Chennaiyin FC,CFC,20,6,263,11,311,17,6,7448,1.0,51,255,663,10271,3,46
5,NorthEast United FC,NEUFC,22,5,235,10,339,33,4,7309,1.0,42,273,695,10377,8,36
6,Bengaluru FC,BFC,20,4,220,7,280,26,8,7547,NaN,61,237,547,10155,5,51
7,FC Goa,FCG,22,4,275,12,327,33,3,10597,4.0,41,300,754,13550,7,35
8,Kerala Blasters FC,KBFC,20,3,289,8,281,23,9,7460,2.0,58,268,651,10212,3,37
9,SC East Bengal,SCEB,20,3,221,8,267,22,9,8193,4.0,64,190,588,10773,3,44
10,Odisha FC,OFC,20,1,205,6,260,25,12,6690,NaN,70,213,600,9386,2,50